apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app_name: gig-ner-wrapper
  name: gig-ner-wrapper
  namespace: prod
spec:
  ports:
    - name: port-8081
      port: 8081
      targetPort: 8081
  selector:
    app_name: gig-ner-wrapper
  type: ClusterIP
